create_clock -name axi_clk -period 10.000 [get_ports aclk]
set_clock_uncertainty -setup 0.200 [get_clocks axi_clk]
set_clock_uncertainty -hold 0.050 [get_clocks axi_clk]
set_input_delay 1.000 -clock axi_clk [remove_from_collection [all_inputs] [get_ports {aclk aresetn}]]
set_output_delay 1.000 -clock axi_clk [all_outputs]
set_false_path -from [get_ports aresetn]
set_load 0.050 [all_outputs]
